// Copied from react-native-svg:
// https://github.com/software-mansion/react-native-svg/blob/b76a21ea7dd2587398c52dad7e53f339add8d2ec/src/xmlTags.ts#L50

const reactNativeSvgElementMappings = {
  circle: 'Circle',
  clipPath: 'ClipPath',
  defs: 'Defs',
  ellipse: 'Ellipse',
  filter: 'Filter',
  feBlend: 'FeBlend',
  feColorMatrix: 'FeColorMatrix',
  feComponentTransfer: 'FeComponentTransfer',
  feComposite: 'FeComposite',
  feConvolveMatrix: 'FeConvolveMatrix',
  feDiffuseLighting: 'FeDiffuseLighting',
  feDisplacementMap: 'FeDisplacementMap',
  feDistantLight: 'FeDistantLight',
  feDropShadow: 'FeDropShadow',
  feFlood: 'FeFlood',
  feGaussianBlur: 'FeGaussianBlur',
  feImage: 'FeImage',
  feMerge: 'FeMerge',
  feMergeNode: 'FeMergeNode',
  feMorphology: 'FeMorphology',
  feOffset: 'FeOffset',
  fePointLight: 'FePointLight',
  feSpecularLighting: 'FeSpecularLighting',
  feSpotLight: 'FeSpotLight',
  feTile: 'FeTile',
  feTurbulence: 'FeTurbulence',
  foreignObject: 'ForeignObject',
  g: 'G',
  image: 'Image',
  line: 'Line',
  linearGradient: 'LinearGradient',
  marker: 'Marker',
  mask: 'Mask',
  path: 'Path',
  pattern: 'Pattern',
  polygon: 'Polygon',
  polyline: 'Polyline',
  radialGradient: 'RadialGradient',
  rect: 'Rect',
  stop: 'Stop',
  svg: 'Svg',
  symbol: 'Symbol',
  text: 'Text',
  textPath: 'TextPath',
  tspan: 'TSpan',
  use: 'Use',
} as const;

export default reactNativeSvgElementMappings;
